language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.3
env:
  global:
    secure: oGRNXaRgbtYOpdera/TeIvWo/NNuaWNJZ3M/L2yN+HmwwyfODCzfEI45G8mxvQ2oTsDwYomOZ3j9oDQgqsibA7BdwmkGEHHcT3ukCIoBOq8HhHjqkxZ3oAAyg+55WDgBp4moQFMWPDuljAG1OXtuHR5Ox/z8/jAVwEah087lkwTrak6veHcpTuhIoR2PZNREVNyrw5Y0YajjH0pKlUKVSzMAbpQdc3mYnHdu67nAw59cztqXtTUPKHL7SeFpIFzqB1aWs59Tzb/oz8djg607P8JmXZNckP7XuQqfpjolqR/ISg03TdDog9vlcb4DG7Cv87kXXLYGK8XNKWpTov9JOMr6pOmfPefb/nUrFcZBInMAcZFAfM+E3OPEmgTyfKAWT3IrWmTkmEJpUK83KY5r4HotxufLNc5WblJfhrL6bQyM6Tl5PcM7yrFMujsX+h7xET9eBqiuwkZaDNetGFMquAWnsYnXqLg7mhdcgNInTHhb9Tkgvi9q/t2Nug+TFFLqYT4GdI6ISdglKlM1vmgZQJjcOhk7Emi5lLCYMR06U8x0LpEd4qsfAdZMyJavg1pB8h2aEcuYuy6yL1ekbkiD/mBk0/3oSAF3PgngdiTabQ8RJ5KSPoKR3kDYrv1ig9GWlDC+VAUDSiffsXA6JwgpVIngDOTusTHqc4LHb+p1Evs=
before_install:
  - gem update --system
  - gem update --remote bundler
  - chmod ugo+x ./setting_ssh.sh
  - chmod ugo+x ./deploy.sh
script:
  - rm -rf _site/*
  - bundle exec jekyll build
after_success:
  - "./setting_ssh.sh"
  - "./deploy.sh"
branches:
  only:
    - source
